name: PR Target Test

on:
  pull_request_target:
   types: [opened, synchronize, closed, edited, reopened]

   branches:
     - dev
     - main

jobs:
  security_check:
    runs-on: img-ubuntu-latest
    steps:
   
      - name: Check Access
        run: |
          echo "Running trigger: ${{ github.event_name }}"
          echo "Target branch: ${{ github.base_ref }}"
          echo "Source branch: ${{ github.head_ref }}"
